server:
  port: 8080
spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      uri: mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
      uri: mongodb://localhost:27017/blog
      grid-fs-database: images
# https://github.com/thymeleaf/thymeleafsandbox-biglist-reactive/blob/8931a34fade5920942bb44bc45265f979545f6a8/src/main/resources/application.properties
  thymeleaf:
    mode: html
    template-resolver-order: 1
    check-template: false
    reactive:
      max-chunk-size: 8192
    chunked-mode-view-names: thymeleaf/*chunked*
logging:
  level:
    org.springframework.web: DEBUG
